config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'rushing/index'

  root 'rushing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rush.rb
class Rush < ApplicationRecord

  def self.to_csv(options = {})
    CSV.generate(headers: true) do |csv|
      csv.add_row column_names
      all.each do |rush|
        values = rush.attributes.values
        csv.add_row values
      end
    end
  end

  def self.search(player)
    where('player LIKE ?', "%#{player}%") || nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rushing_controller.rb
class RushingController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    if player_query
      @rushes = Rush.search(@player)
    else
      @rushes = Rush.all
    end

    @rushes = @rushes.order(@sort_column + " " + @sort_direction) if sort_column && sort_direction

    respond_to do |format|
      format.html
      format.csv { send_data @rushes.to_csv, filename: "rushing-info-#{Date.today}.csv" }
    end
  end

  private

  def sort_column
    @sort_column = params[:column] || @sort_column
  end

  def sort_direction
    @sort_direction = params[:direction] || @sort_direction
  end

  def player_query
    @player = params[:search] || @player
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title=nil, search=nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction_sort = ((column == sort_column) && (sort_direction == "asc")) ? "desc" : "asc"
    link_to title, {column: column, direction: direction_sort, search: search}, {class: css_class}
  end
end

app/helpers/rushing_helper.rb
module RushingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <system.web>
      <globalization culture="en-US" uiCulture="en-US" />
    </system.web>
    <title>NflRushing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rushing/index.html.erb
<div class="download">
  <%= link_to "Download CSV", rushing_index_path(format: "csv", direction: @sort_direction, column: @sort_column, search: @player) %>
</div>

<%= form_tag(rushing_index_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>
<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th>Position</th>
    <th>Rushing Attempts/Game Avg</th>
    <th>Rushing Attempts</th>
    <th><%= sortable "yds", "Total Rushing Yards", @player %></th>
    <th>Rushing Avg Yards/Attempt</th>
    <th>Rushing Yards/Game</th>
    <th><%= sortable "td", "Total Rushing Touchdowns", @player %></th>
    <th><%= sortable "lng", "Longest Rush", @player %></th>
    <th>Rushing First Downs</th>
    <th>Rushing First Downs %</th>
    <th>Rushing 20+ Yards Each</th>
    <th>Rushing 40+ Yards Each</th>
    <th>Rushing Fumbles</th>
  </tr>
<% @rushes.each do |rush| %>
  <tr>
    <td><%= rush.player %></td>
    <td><%= rush.team %></td>
    <td><%= rush.pos.to_s %></td>
    <td><%= rush.att %></td>
    <td><%= rush.att_per_g %></td>
    <td><%= rush.yds %></td>
    <td><%= rush.avg %></td>
    <td><%= rush.yds_per_g %></td>
    <td><%= rush.td %></td>
    <td><%= rush.lng %></td>
    <td><%= rush.first %></td>
    <td><%= rush.first_percent %></td>
    <td><%= rush.twenty_plus %></td>
    <td><%= rush.forty_plus %></td>
    <td><%= rush.fum %></td>
  </tr>
<% end %>
</table>